### PR TITLE
fix: Add LanguageManager to DataWrapper and filter pins

### LINKED ISSUE #68: Add query condition for current language
Proposed solution:
Add the language manager service to the DataWrapper service.
https://github.com/open-y-subprojects/openy_custom/blob/main/openy_data_wrapper/src/DataWrapper.php

Add a query condition to filter by the current language:
https://github.com/open-y-subprojects/openy_custom/blob/main/openy_data_wrapper/src/DataWrapper.php#L120

### PR DESCRIPTION
**Pull request by froboy**
closes #68.

Requires a version bump (to 2.5.0) due to additional argument in constructor.

### CODE REVIEW

**Review by andrebonon — APPROVED** [review]

File: openy_data_wrapper/src/DataWrapper.php [hunk 1]
```diff
@@ -117,11 +128,13 @@ public function getPins($type, $id = NULL) {
       $location_ids[] = $id;
     }
     else {
+      $langcode = $this->languageManager->getCurrentLanguage()->getId();
       $location_ids = $this->entityTypeManager->getStorage('node')
         ->getQuery()
         ->accessCheck(FALSE)
         ->condition('type', $type)
         ->condition('status', 1)
+        ->condition('langcode', $langcode)
```
Comment (podarok) [inline openy_data_wrapper/src/DataWrapper.php:137]: what happens with und/en landcodes?
There is a history of language, when node created without translation enabled and then language enabled on a site there will be nodes `und` and `en`

We need to take care about default language before translation enabled on a site @froboy

File: openy_data_wrapper/src/DataWrapper.php [hunk 2]
```diff
@@ -214,11 +227,13 @@ public function getBranchPins($id = NULL) {
    */
   public function getLocations() {
     $data = [];
+    $langcode = $this->languageManager->getCurrentLanguage()->getId();
 
     $location_ids = $this->entityTypeManager->getStorage('node')
       ->getQuery()
       ->accessCheck(FALSE)
       ->condition('type', 'branch')
+      ->condition('langcode', $langcode)
```
Comment (podarok) [inline openy_data_wrapper/src/DataWrapper.php:236]: same https://github.com/open-y-subprojects/openy_custom/pull/70/files#r1559845278

**Comment by podarok** [comment]
needs your feedback @froboy

File: openy_data_wrapper/src/DataWrapper.php (hunk 1 above)
Comment (froboy) [reply openy_data_wrapper/src/DataWrapper.php:137]: SCR-20240430-magd

@podarok I tested on a stock install of the distro and it seems like it's impossible to have entities with `und` language codes. On first install of Drupal core, you're required to select a language. Even if you do not enable translations, every entity you create still has a language code from core, completely independent of translation.

SCR-20240430-magd-2

So, I think this can move forward.
