### PR TITLE
Only get SVG file if it actually exists

### LINKED ISSUE #4: "Failed to open stream ..." when svg file is missing
```
Message | Warning: file_get_contents(public://strength-equipment.svg): Failed to open stream: "Drupal\Core\StreamWrapper\PublicStream::stream_open" call failed in Drupal\openy_svg_formatter\Plugin\Field\FieldFormatter\OpenYSvgFormatter->viewElements() (line 46 of /var/www/html/docroot/modules/contrib/openy_custom/openy_svg_formatter/src/Plugin/Field/FieldFormatter/OpenYSvgFormatter.php)
```

These sorts of warnings can be thrown when SVGs are missing. There is a long-standing Drupal issue related to this but it seems to have been forgotten: https://www.drupal.org/project/drupal/issues/1803330. We can fix it ourselves here while we wait.

### PR DESCRIPTION
**Pull request by froboy**
Resolves #4. Solution taken from https://www.drupal.org/project/drupal/issues/1803330

### CODE REVIEW

File: openy_svg_formatter/src/Plugin/Field/FieldFormatter/OpenYSvgFormatter.php [hunk 1]
```diff
@@ -43,7 +43,12 @@ public function viewElements(FieldItemListInterface $items, $langcode) {
     foreach ($items as $delta => $item) {
       if ($item->entity) {
         $uri = $item->entity->getFileUri();
-        $svg = file_get_contents($uri);
+        $svg = '';
+        // Make sure the file actually exists.
+        if (file_exists($uri)) {
+          \Drupal::logger('locale')->warning('Could not open SVG file: %s', ['%s' => $uri]);
```
Comment (podarok) [inline openy_svg_formatter/src/Plugin/Field/FieldFormatter/OpenYSvgFormatter.php:49]: How often are we going to have this code executed?
I'd like to get rid of logging file doesn't exist for performance reason

**Review by podarok — COMMENTED** [review]
Let's remove possible overwhelmed logging

File: openy_svg_formatter/src/Plugin/Field/FieldFormatter/OpenYSvgFormatter.php (hunk 1 above)
Comment (froboy) [reply openy_svg_formatter/src/Plugin/Field/FieldFormatter/OpenYSvgFormatter.php:49]: @podarok this only runs on cache-rebuild, so it shouldn't be often.
